In [ ]:
import tweepy
import pandas as pd
import re, string

In [ ]:
final_my_tweet= ['Tweets',
 '@balen_shah1 Good 😊😊',
 '@belakoboli khasai kei gareko ta xainan balen dai le yeti bidi jholey tarika le raja sanga comapre nagareko vaye hu… https://t.co/UOBy38KitJ',
 'The master of corruption of my country: The President, Prime Minister, Minister, MP, MLA, Mayor and even the Ward C… https://t.co/tOaO6Vydvu',
 '@belakoboli One of the extremely rare occasions where I happen to agree with this guy, even if partially. Although… https://t.co/zq3ORYvsvy',
 'Balen during weekends! 🤔\n\n https://t.co/OS44uOMGjE',
 'Balen and Sampang effect in federal elections https://t.co/6lC0qdePoG via @TheAnnaExpress',
 '@machiel1 @albertheijn Whut? Balen!',
 '@BaldipChauhan @RabindraMishra Rabindra Mishra will never win. He ended his political career the moment he decided… https://t.co/9RucvbpnUm',
 '@balen_shah1 Proud of you @ShahBalen',
 'balen’s wife… i wasn’t familiar with his game',
 '@sanghiyawtie Balen is leading the metropolis while serving. k bhaneko mijyu yesto?😩',
 '@balen_shah1 Really nice pict thank you  keep going sir please I from Boston please 🙏',
 'RT @RoyalFamily: His Majesty The King gives a\xa0personal\xa0declaration at today’s Accession Council, where he was formally proclaimed King Char…',
 '@balen_shah1 Beautiful',
 '@kandeldai Jealousy against Balen',
 'RT @sanzinme: Hait #Balen 🔥🔥 https://t.co/QWjkBRUnFT',
 'Songs of LANY 🎵 🎶',
 'ELECTION 2022\n\n"Rise of independent candidates like Balen and Sampang at the local level has paved the path for sev… https://t.co/mmJVv2q645',
 '@balen_shah1 Fake Acount',
 '@balen_shah1 Good 🙏🙏',
 '@balen_shah1 Thank.',
 "RT @ShellenbergerMD: That's not the end of the story, of course. Farmers can fight back. We can show solidarity with them. \n\nIn Sri Lanka t…",
 "So nicely expressed ! Balen and the team should heed on the author's feedback. \n\n@kathmandupost, hilarious is the m… https://t.co/gwW3hknZHY",
 '@balen_shah1 Hero of nation',
 '@rameshore Balen is able to deliver, because he is professional and free to take his own decisions, unfettered by c… https://t.co/VDWM4kjDO0',
 '@balen_shah1 rell time rell king i love ..my heart contact fell',
 '@juction4love Before Balen, the President and the Prime Minister showed zero and\nthinking👇 🤔 👌😋 \nSame photo 👇👇terro… https://t.co/3b3CCb8x3V',
 'Balen is no less than a great celebrity!\n#BalenSupporter ✌️',
 "RT @RaameshKoirala: Is Balen a DON?\nNO.\nHe deserves extra 'e'.\nWell DONE!\n🙏🙏🙏🙏🙏",
 "When you're hangry af at a momo pasal and the server is down so you can't even watch balen's dozer on tiktok https://t.co/2ripYTt0mO",
 'I wonder will rabindra misra accept balen as new king when monarchy gets back?🤔',
 'RT @SarcasmNpl: Nothing interesting, just Routiney pretending Balen to be the king. https://t.co/0urZ0GuvGX',
 '@balen_shah1 Is Balen compairing himself with the king.... OMG ,',
 'but is Balen a leader at all? Isn’t he a public servant? https://t.co/USTKazCR0T',
 '@balen_shah1 Great Job',
 'RT @RONBupdates: Kathmandu Metro Mayor Balen Shah gave his presence during Indra Jatra at Basantapur yesterday and huge crowd of people was…',
 'RT Emily Ratajkowski slays Ratajkowski wearing Knwls Halcyon Long-Sleeved Top, Knwls Halcyon Flared Leggings, Balen… https://t.co/MRSzQQp7iF',
 '@NirmalPrasai5 Nirmal jee, I still remember you arguing with me on Twitter during the Mayoral election, saying Bale… https://t.co/oEq8stvZfp',
 'RT @arundadhikary: अब अरु लाई ridicule गरेर भोट जितिदैन ! Those days are gone ! You must stand out on your own merit without belittling you…',
 'RT @LawaRashid: Summer dump https://t.co/doppzTbq0t',
 'versace bottega praga balen vuitton dior givenchy',
 "bALEN'S Craze is evidence of hunger for good leadership in Nepal",
 '@balen_shah1 Nice pic',
 'The Balen brothers blew through the competition winning the first annual 2A District Doubles Invite tournament! Con… https://t.co/jwrp7ffmct',
 '@Split_72 How do you make SO MANY LEVELS',
 '@ShashankGhimir8 @balen_shah1 It’s fan page 😁',
 'RT @NoNext_Question: The video shows people’s craze and support for Kathmandu Metropolis Mayor Balen Shah during Indra Jatra festival held…',
 '@balen_shah1 Great effort. Well-done Balen, salute you 🌹',
 '@balen_shah1 Really proud of you and shine like our king  birendra. Always think about our nepali people and I am h… https://t.co/eJSsC2caiQ',
 '@balen_shah1 Keep up the good work ☺️',
 'Balen turning into a revolution. https://t.co/ygiKnuzHfe',
 '@parajulippradip @balen_shah1 This is the pic of the decade ❣️',
 'RT @SamratSpeaks: Balen is making us dormant folks realize what a leader should be, something we never had so far. Never in my life had I s…',
 '@balen_shah1 Great work',
 'It’s not a purse. It’s a Balen.',
 '@Dipendra02468 @balen_shah1 So it has been warned',
 '@Anjita_pandey Thnak you. I willbe there. Balen ko sahar ma ni aainus.. https://t.co/zZx4DQXzJW',
 'RT @_bishab: Balen turning into a revolution. https://t.co/ygiKnuzHfe',
 '@ShahBalen 200-300 paid actor everyday follows balen tetro berojgar ni chaina hola ni free ma nara lagayera balen b… https://t.co/yfVtLqPdKe',
 '@dipeshrisal This is another extreme ..sure Balen realizes it. Also King B did not have Balen kind of personality -… https://t.co/U6rjUeEiso',
 '@balen_shah1 Great job 👏',
 '@bahunnaran Balen is not king 👑💯👑 ok ...',
 '@theomeereboer Shit. Balen',
 '@creo_music I will gladly play the triple a price of 60 United States dollars for a Creo game',
 'RT @drs1k: @juction4love Before Balen, the President and the Prime Minister showed zero and\nthinking👇 🤔 👌😋 \nSame photo 👇👇terrorist https://…',
 "@iRiskant_ @NS_online Blegh, da's balen. 💔",
 '@balen_shah1 nice pic ....go ahead balen ji']

In [ ]:
# Text pre-processing
def get_normalize(text):
    text = re.sub(r'\&\w*;','',text)
    text = re.sub('@[^\s]+','',text)
    text = re.sub(r'\$\w*','',text)
    text = text.lower()
    text = re.sub(r'https?:\/\/.*\/\w*','',text)
    text = re.sub(r'#\w*','',text)
    text = re.sub(r'[' + string.punctuation.replace('@','') + ']+',' ',text)
    text = re.sub(r'\b\w{1,2}\b','',text)
    text = re.sub(r'\s\s+',' ',text)
    text = re.sub("[^a-zA-Z]", " ", text)
    text = text.lstrip(' ')
    text = ''.join(c for c in text if c <= '\uFFFF')
    return text
j = 0
for i in final_my_tweet:
  final_my_tweet[j]=get_normalize(str(i))
  j = j+1
final_my_tweet

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3138/2827137759.py:4: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub('@[^\s]+','',text)

['tweets',
 'good   ',
 'khasai kei gareko xainan balen dai yeti bidi jholey tarika raja sanga comapre nagareko vaye   ',
 'the master corruption country the president prime minister minister mla mayor and even the ward   ',
 'one the extremely rare occasions where happen agree with this guy even partially although  ',
 'balen during weekends   ',
 'balen and sampang effect federal elections via ',
 'whut balen ',
 'rabindra mishra will never win ended his political career the moment decided  ',
 'proud you ',
 'balen  wife  wasn  familiar with his game',
 'balen leading the metropolis while serving bhaneko mijyu yesto  ',
 'really nice pict thank you keep going sir please from boston please  ',
 'his majesty the king gives personal declaration today  accession council where was formally proclaimed king char ',
 'beautiful',
 'jealousy against balen',
 'hait    ',
 'songs lany    ',
 'election      rise independent candidates like balen and sampang the local level has paved the path for sev  ',
 'fake acount',
 'good   ',
 'thank ',
 'that not the end the story course farmers can fight back can show solidarity with them sri lanka  ',
 'nicely expressed balen and the team should heed the author feedback hilarious the   ',
 'hero nation',
 'balen able deliver because professional and free take his own decisions unfettered   ',
 'rell time rell king love heart contact fell',
 'before balen the president and the prime minister showed zero and thinking       same photo   terro  ',
 'balen less than great celebrity   ',
 'balen don deserves extra well done      ',
 'when you hangry momo pasal and the server down you can even watch balen dozer tiktok ',
 'wonder will rabindra misra accept balen new king when monarchy gets back  ',
 'nothing interesting just routiney pretending balen the king ',
 'balen compairing himself with the king omg ',
 'but balen leader all isn  public servant ',
 'great job',
 'kathmandu metro mayor balen shah gave his presence during indra jatra basantapur yesterday and huge crowd people was ',
 'emily ratajkowski slays ratajkowski wearing knwls halcyon long sleeved top knwls halcyon flared leggings balen  ',
 'nirmal jee still remember you arguing with twitter during the mayoral election saying bale  ',
 'ridicule         those days are gone you must stand out your own merit without belittling you ',
 'summer dump ',
 'versace bottega praga balen vuitton dior givenchy',
 'balen craze evidence hunger for good leadership nepal',
 'nice pic',
 'the balen brothers blew through the competition winning the first annual district doubles invite tournament con  ',
 'how you make many levels',
 'fan page  ',
 'the video shows people  craze and support for kathmandu metropolis mayor balen shah during indra jatra festival held ',
 'great effort well done balen salute you  ',
 'really proud you and shine like our king birendra always think about our nepali people and   ',
 'keep the good work   ',
 'balen turning into revolution ',
 'this the pic the decade   ',
 'balen making dormant folks realize what leader should something never had far never life had  ',
 'great work',
 'not purse   balen ',
 'has been warned',
 'thnak you willbe there balen sahar aainus ',
 'balen turning into revolution ',
 'paid actor everyday follows balen tetro berojgar chaina hola free nara lagayera balen   ',
 'this another extreme sure balen realizes also king did not have balen kind personality   ',
 'great job  ',
 'balen not king     ',
 'shit balen',
 'will gladly play the triple price united states dollars for creo game',
 'before balen the president and the prime minister showed zero and thinking       same photo   terrorist https  ',
 'blegh balen  ',
 'nice pic ahead balen ']

In [ ]:
tweets = {'tweets':final_my_tweet}
data = pd.DataFrame(tweets)
data

                                               tweets
0                                              tweets
1                                             good
2   khasai kei gareko xainan balen dai yeti bidi j...
3   the master corruption country the president pr...
4   one the extremely rare occasions where happen ...
..                                                ...
63                                         shit balen
64  will gladly play the triple price united state...
65  before balen the president and the prime minis...
66                                      blegh balen
67                              nice pic ahead balen

[68 rows x 1 columns]

In [ ]:
new_data = data.drop_duplicates(subset="tweets") #to drop retweets and repeated rows #subset is a keyword in pandas with column value as "Tweets" to indicate the column with duplicate text
new_data.to_csv('/content/filtered_data.csv')
new_data

                                               tweets
0                                              tweets
1                                             good
2   khasai kei gareko xainan balen dai yeti bidi j...
3   the master corruption country the president pr...
4   one the extremely rare occasions where happen ...
..                                                ...
63                                         shit balen
64  will gladly play the triple price united state...
65  before balen the president and the prime minis...
66                                      blegh balen
67                              nice pic ahead balen

[66 rows x 1 columns]

In [ ]:
from textblob import TextBlob

new_data[['Polarity', 'Subjectivity']] = new_data['tweets'].apply(
    lambda Text: pd.Series(TextBlob(Text).sentiment))
new_data

/tmp/ipykernel_3138/3354968942.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data[['Polarity', 'Subjectivity']] = new_data['tweets'].apply(
/tmp/ipykernel_3138/3354968942.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data[['Polarity', 'Subjectivity']] = new_data['tweets'].apply(

                                               tweets  Polarity  Subjectivity
0                                              tweets      0.00         0.000
1                                             good         0.70         0.600
2   khasai kei gareko xainan balen dai yeti bidi j...      0.00         0.000
3   the master corruption country the president pr...      0.00         0.000
4   one the extremely rare occasions where happen ...      0.10         0.600
..                                                ...       ...           ...
63                                         shit balen     -0.20         0.800
64  will gladly play the triple price united state...      0.05         0.700
65  before balen the president and the prime minis...      0.00         0.125
66                                      blegh balen        0.00         0.000
67                              nice pic ahead balen       0.60         1.000

[66 rows x 3 columns]

In [ ]:
new_data.to_csv('/content/filtered_data.csv')

In [ ]:
y = new_data['Polarity']
positive = 0
negative = 0
neutral = 0

for a in y:
    if a>0:
     positive=positive+1
    elif a<0:
     negative=negative+1
    else:
     neutral=neutral+1
numberOfTweetsAnalysed= positive+negative+neutral
print('Number of Tweets Analysed = '+str(numberOfTweetsAnalysed))
print('Positive tweets = '+str(positive))
print('Negative tweets = '+str(negative))
print('Neutral tweets = '+str(neutral))

Number of Tweets Analysed = 66
Positive tweets = 29
Negative tweets = 5
Neutral tweets = 32

In [ ]:
df1 = new_data[new_data['Polarity'] > 0]
df1['sentiment'] ='Positive'
df2 = new_data[new_data['Polarity'] < 0]
df2['sentiment'] ='Negative'
df3 = new_data[new_data['Polarity'] == 0]
df3['sentiment'] ='Neutral'

new_data = pd.concat([df1,df2,df3]).sample(frac = 1)
new_data

/tmp/ipykernel_3138/1103267366.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['sentiment'] ='Positive'
/tmp/ipykernel_3138/1103267366.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['sentiment'] ='Negative'
/tmp/ipykernel_3138/1103267366.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['sentiment'] ='Neutral'

,tweets,Polarity,Subjectivity,sentiment
17,songs lany,0.0,0.0000,Neutral
36,kathmandu metro mayor balen shah gave his pres...,0.4,0.9000,Positive
39,ridicule those days are gone you must ...,0.6,1.0000,Positive
66,blegh balen,0.0,0.0000,Neutral
53,balen making dormant folks realize what leader...,0.1,1.0000,Positive
...,...,...,...,...
8,rabindra mishra will never win ended his polit...,-0.2,0.2500,Negative
6,balen and sampang effect federal elections via,0.0,0.0000,Neutral
43,nice pic,0.6,1.0000,Positive
12,really nice pict thank you keep going sir plea...,0.6,1.0000,Positive
18,election rise independent candidates like...,0.0,0.0625,Neutral